version: "3.1"

services:
  app:
    container_name: link-shortener-fastapi
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./migrations/versions:/app/migrations/versions
    depends_on:
      - db
  db:
    image: postgres:16.1
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    env_file:
      - .env.dev
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
volumes:
  postgres_volume: