"""create table Link

Revision ID: b590e2a9d8fc
Revises:
Create Date: 2024-01-25 13:59:13.760341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b590e2a9d8fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('link_id', sa.String(), nullable=False),
                    sa.Column('origin_link', sa.String(), nullable=False),
                    sa.Column('shortened_link', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link')
    # ### end Alembic commands ###
